resources:
  - name: dwpdigital-dataworks-alertmanager-sns-forwarder
    type: registry-image-resource
    source:
      repository: dwpdigital/dataworks-alertmanager-sns-forwarder
    check_every: 5m

  - name: ecr-dwpdigital-dataworks-alertmanager-sns-forwarder-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-alertmanager-sns-forwarder"

  - name: ecr-dwpdigital-dataworks-alertmanager-sns-forwarder
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-alertmanager-sns-forwarder"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-dataworks-alertmanager-sns-forwarder-dev
    serial_groups: [dataworks-alertmanager-sns-forwarder]
    plan:
      - get: dwpdigital-dataworks-alertmanager-sns-forwarder
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-alertmanager-sns-forwarder-dev
        params:
          image: "dwpdigital-dataworks-alertmanager-sns-forwarder/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-dataworks-alertmanager-sns-forwarder
    serial_groups: [dataworks-alertmanager-sns-forwarder]
    plan:
      - get: dwpdigital-dataworks-alertmanager-sns-forwarder
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-alertmanager-sns-forwarder
        params:
          image: "dwpdigital-dataworks-alertmanager-sns-forwarder/image.tar"
        attempts: 3
